name: chronos_launcher
description: Chronos Launcher - A Premium Matte Carbon Focus Launcher by Varshan.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  just_audio: ^0.9.36
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/rain_lofi.mp3
    - assets/audio/deep_synth.mp3
    - assets/audio/mellow_piano.mp3
