apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.varshan.chronoslauncher'
version = '1.0.0'

android {
  compileSdkVersion 34

  defaultConfig {
    minSdkVersion 21
    targetSdkVersion 34
    versionCode 1
    versionName "1.0.0"
  }

  lintOptions {
    abortOnError false
  }
  
  namespace "com.varshan.chronoslauncher"
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.22"
}
